baseURL = "https://scala-noob.de/"
languageCode = "de-de"
title = "Scala n00b"
theme = "beautifulhugo"
pygmentsuseclasses = true

[[menu.main]]
    name = "Über"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Impressum"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "impressum"
    url = "/impressum/"


